[package]
name = "rdst"
description = "A flexible parallel unstable radix sort that supports sorting by any arbitrarily defined sequence of bytes."
version = "0.5.1"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Nessex/rdst"
homepage = "https://github.com/Nessex/rdst"
categories = ["algorithms"]
keywords = ["radix","sort","rayon","parallel","multithreaded"]
documentation = "https://docs.rs/rdst/"

[features]
default = ["default-implementations"]
bench = []
default-implementations = []

[dependencies]
rayon = "1.5.1"
num_cpus = "1.13.0"
nanorand = "0.6.1"
arbitrary-chunks = "0.2.1"

[dev-dependencies]
voracious_radix_sort = { version = "1.1.0", features = ["voracious_multithread"] }
