[package]
name = "radix-sort"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.5.1"

[dev-dependencies]
rand = "0.8.4"
voracious_radix_sort = { version = "1.1.0", features = ["voracious_multithread"] }
num_cpus = "1.13.0"