[package]
name = "rdst"
description = "A flexible parallel unstable radix sort that supports sorting by any arbitrarily defined sequence of bytes."
version = "0.18.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Nessex/rdst"
homepage = "https://github.com/Nessex/rdst"
categories = ["algorithms"]
keywords = ["radix","sort","rayon","parallel","multithreaded"]
documentation = "https://docs.rs/rdst/"

[features]
default = ["default-implementations"]
bench = ["criterion", "block-pseudorand"]
tuning = ["nanorand", "rlp-iter", "block-pseudorand", "oxigen", "rand", "lazy_static"]
default-implementations = []
work_profiles = []

[dependencies]
rayon = "1.5.1"
arbitrary-chunks = "0.3.0"
try-mutex = "0.4.0"
partition = "0.1.2"
criterion = { version = "0.3.5", optional = true }
block-pseudorand = { version = "0.1.1", optional = true }
nanorand = { version =  "0.6.1", optional = true }
rlp-iter = { version = "0.2.0", optional = true }
oxigen = { version = "2.2.2", git = "https://github.com/Nessex/oxigen.git", branch = "nessex-single-threaded", optional = true, features=["global_cache"] }
rand = { version = "0.7", optional = true, features = ["small_rng"] }
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]
voracious_radix_sort = { version = "1.1.0", features = ["voracious_multithread"] }
num_cpus = "1.13.0"
criterion = "0.3.5"
block-pseudorand = "0.1.1"

[profile.release]
codegen-units = 1
opt-level = 3

[[bin]]
name = "monte-carlo-tuning"
path = "src/monte_carlo.rs"
required-features = [ "tuning" ]

[[bin]]
name = "ga-tuning"
path = "src/ga_tuning.rs"
required-features = [ "tuning" ]

[[bench]]
name = "full_sort"
harness = false

[[bench]]
name = "tuning_parameters"
harness = false

[[example]]
name = "profiling"
test = false
required-features = ["bench"]

[[example]]
name = "timings"
test = false
required-features = ["bench"]
