[package]
name = "fixture"
description = "Used to check that the library still works even when included externally"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdst = { path = "../" }
